version: "3"

services:
  postgres:
    image: postgres:17-alpine
    container_name: planner-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planner_db
    ports:
      - "5432:5432"
